# Generated by Django 5.1.2 on 2024-11-02 10:28

import uuid

import django.core.validators
import django.utils.timezone
from django.db import migrations, models

import apps.api.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URLInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date time on which the object was created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was updated.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        db_index=True,
                        help_text="The URL of the page",
                        unique=True,
                        validators=[apps.api.validators.URLValidator],
                        verbose_name="URL",
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[("http", "Http"), ("https", "Https")],
                        help_text="The protocol of the URL",
                        max_length=5,
                        verbose_name="Protocol",
                    ),
                ),
                (
                    "subdomain",
                    models.CharField(
                        blank=True,
                        help_text="The subdomain of the URL",
                        max_length=255,
                        null=True,
                        verbose_name="Subdomain",
                    ),
                ),
                (
                    "domain_name",
                    models.CharField(
                        help_text="The domain name of the URL",
                        max_length=255,
                        validators=[django.core.validators.DomainNameValidator],
                        verbose_name="Domain name",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="The title of the page", max_length=255, verbose_name="Title"),
                ),
                (
                    "images",
                    models.JSONField(
                        blank=True,
                        help_text="The URLs of all the images <img>",
                        null=True,
                        verbose_name="Images urls",
                    ),
                ),
                (
                    "stylesheets_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="The number of stylesheets present in the html of the page",
                        verbose_name="Stylesheets count",
                    ),
                ),
            ],
            options={
                "verbose_name": "URL info",
                "verbose_name_plural": "URL infos",
                "db_table": "url_info",
            },
        ),
    ]
